# Generated by Django 6.0.3 on 2026-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_color_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, related_name='color_variants', to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variants',
            field=models.ManyToManyField(blank=True, related_name='size_variants', to='products.sizevariant'),
        ),
    ]
